import "./globals.css";
import React from "react";
import {Metadata} from "next";
import QueryWrapper from "@/components/QueryWrapper";
import AuthContext from "@/components/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge"/>
        <title>Secure Key</title>
      </head>
      <body>
      <div className="bg">
        <QueryWrapper>
          <AuthContext>
              {children}
          </AuthContext>
        </QueryWrapper>
      </div>
      </body>
      </html>
  );
}
